{% set name = "hda" %}
{% set version = "2.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: fb19ade5a57e0b0a7c76e51c8f7080a0341cae6226a4804fae5a453f63723e3e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.5.0
    - tqdm

test:
  imports:
    - hda

about:
  home: "https://github.com/ecmwf/hda"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "API to harmonised data access for DIAS/WEkEO"
  doc_url: https://hda.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/hda

extra:
  recipe-maintainers:
    - gbiavati
