{% set name = "hda" %}
{% set version = "2.20" %}
{% set python_min = "3.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c1a709435abbf2dbba9648349c0da6949ba4270ed49c922c788af7431f8c13c2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}.*
  run:
    - python >={{ python_min }}
    - requests >=2.5.0
    - tqdm

test:
  imports:
    - hda

about:
  home: "https://github.com/ecmwf/hda"
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: "API to harmonised data access for DIAS/WEkEO"
  doc_url: https://hda.readthedocs.io/en/latest/
  dev_url: https://github.com/ecmwf/hda

extra:
  recipe-maintainers:
    - gbiavati
